package pourCommencer;

public enum Event {
	DUST_GENERATED,
	DUST_VACCUMED,
	JEWELRY_GENERATED,
	JEWELRY_GATHERED,
	JEWELRY_VACCUMED,
	AGENT_MOVED,
	AGENT_HIT_NORTH,
	AGENT_HIT_SOUTH,
	AGENT_HIT_WEST,
	AGENT_HIT_EST,
	VOID_VACCUMED,
	VOID_GATHERED
}
